@startuml tetris 
class Jugador
class Teclado
class Campo 
class Fondo 
class Tetromino
class Mino 
class Puntaje
class Color
class Forma
class 

Mino *-- Color
Mino *-- Puntaje
Puntaje *-- Color

Jugador *-- Puntaje
Jugador o-- Teclado
Fondo *--Campo
Mino o-- Campo
Tetromino --|> Mino
Tetromino o-- Campo
Tetronimo o-- Color
Tetronimo o-- Forma
Color *-- Tetromino

@enduml